window.RESTAURANTS = [
  {
    id: "CB01",
    name: "何洪記",
    en_name: "Ho Hung Kee",
    area: "銅鑼灣",
    area_en: "Causeway Bay",
    cuisine: "粵菜",
    cuisine_en: "Cantonese",
    price: "$$$",
    score: 5,
    tags: [
      "點心",
      "米芝蓮",
      "燒味",
      "dim sum",
      "michelin",
      "cantonese"
    ],
    desc: "米芝蓮推薦粵菜，雲吞麵同燒味都非常出色。",
    desc_en: "Michelin-recommended Cantonese restaurant famous for wonton noodles and roast meats.",
    map: "https://maps.google.com/?q=22.2805,114.1829",
    image_url: "https://images.unsplash.com/photo-1585032226651-759b368d7246",
    lat: 22.2805,
    lng: 114.1829
  },
  {
    id: "CB02",
    name: "Roganic",
    en_name: "Roganic",
    area: "銅鑼灣",
    area_en: "Causeway Bay",
    cuisine: "英國菜",
    cuisine_en: "British Fine Dining",
    price: "$$$$",
    score: 5,
    tags: [
      "fine dining",
      "英國菜",
      "高級",
      "約會",
      "restaurant",
      "modern european"
    ],
    desc: "現代英國 fine dining，適合約會或慶祝。",
    desc_en: "Modern British fine dining, perfect for special occasions.",
    map: "https://maps.google.com/?q=22.2799,114.1832",
    image_url: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0",
    lat: 22.2799,
    lng: 114.1832
  },
  {
    id: "CB03",
    name: "薄餅之母",
    en_name: "Mother of Pizzas",
    area: "銅鑼灣",
    area_en: "Causeway Bay",
    cuisine: "意大利菜",
    cuisine_en: "Italian Pizza",
    price: "$$$",
    score: 4,
    tags: [
      "pizza",
      "意大利",
      "薄餅",
      "casual",
      "italian"
    ],
    desc: "人氣手工 pizza 店，氣氛輕鬆。",
    desc_en: "Popular handmade pizza spot with a casual vibe.",
    map: "https://maps.google.com/?q=22.2810,114.1845",
    image_url: "https://images.unsplash.com/photo-1513104890138-7c749659a591",
    lat: 22.281,
    lng: 114.1845
  },
  {
    id: "CB04",
    name: "Green Bowl",
    en_name: "Green Bowl",
    area: "銅鑼灣",
    area_en: "Causeway Bay",
    cuisine: "健康餐",
    cuisine_en: "Healthy Salad",
    price: "$$",
    score: 4,
    tags: [
      "健康",
      "沙律",
      "輕食",
      "healthy",
      "salad",
      "light"
    ],
    desc: "低卡健康餐，適合想食清淡啲。",
    desc_en: "Healthy low-calorie meals, great for light eating.",
    map: "https://maps.google.com/?q=22.2800,114.1840",
    image_url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
    lat: 22.28,
    lng: 114.184
  },
  {
    id: "FH01",
    name: "魚事者",
    en_name: "Fisholic",
    area: "炮台山",
    area_en: "Fortress Hill",
    cuisine: "創意料理",
    cuisine_en: "Fusion Noodles",
    price: "$",
    score: 5,
    tags: [
      "魚麵",
      "米芝蓮",
      "創意",
      "fusion",
      "noodles",
      "bib gourmand"
    ],
    desc: "創意魚麵料理，米芝蓮推介。",
    desc_en: "Creative fish noodle dishes, Michelin Bib Gourmand.",
    map: "https://maps.google.com/?q=22.2880,114.1910",
    image_url: "https://images.unsplash.com/photo-1555126634-323283e090fa",
    lat: 22.288,
    lng: 114.191
  },
  {
    id: "FH02",
    name: "拉麵街",
    en_name: "Ramen Street",
    area: "炮台山",
    area_en: "Fortress Hill",
    cuisine: "日本拉麵",
    cuisine_en: "Japanese Ramen",
    price: "$$",
    score: 4,
    tags: [
      "拉麵",
      "日本",
      "宵夜",
      "ramen",
      "japanese",
      "late night"
    ],
    desc: "濃厚湯底拉麵，宵夜一流。",
    desc_en: "Rich ramen broth, great for late-night meals.",
    map: "https://maps.google.com/?q=22.2890,114.1905",
    image_url: "https://images.unsplash.com/photo-1557872943-16a5ac26437e?q=80&w=1200&auto=format&fit=crop",
    lat: 22.289,
    lng: 114.1905
  },
  {
    id: "FH03",
    name: "BBQ House",
    en_name: "BBQ House",
    area: "炮台山",
    area_en: "Fortress Hill",
    cuisine: "韓國燒肉",
    cuisine_en: "Korean BBQ",
    price: "$$$",
    score: 4,
    tags: [
      "韓燒",
      "燒肉",
      "朋友",
      "korean",
      "bbq",
      "grill"
    ],
    desc: "熱鬧韓燒，適合朋友聚餐。",
    desc_en: "Lively Korean BBQ, great for group dining.",
    map: "https://maps.google.com/?q=22.2885,114.1920",
    image_url: "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd",
    lat: 22.2885,
    lng: 114.192
  },
  {
    id: "CEN01",
    name: "牛扒館",
    en_name: "Steak Prime",
    area: "中環",
    area_en: "Central",
    cuisine: "西餐牛扒",
    cuisine_en: "Steakhouse",
    price: "$$$$",
    score: 5,
    tags: [
      "牛扒",
      "西餐",
      "約會",
      "steak",
      "western",
      "fine dining"
    ],
    desc: "高級牛扒館，適合慶祝或約會。",
    desc_en: "Premium steakhouse, perfect for dates and celebrations.",
    map: "https://maps.google.com/?q=22.2815,114.1580",
    image_url: "https://images.unsplash.com/photo-1544025162-d76694265947",
    lat: 22.2815,
    lng: 114.158
  },
  {
    id: "CEN02",
    name: "Taco Fiesta",
    en_name: "Taco Fiesta",
    area: "中環",
    area_en: "Central",
    cuisine: "墨西哥菜",
    cuisine_en: "Mexican",
    price: "$$",
    score: 4,
    tags: [
      "taco",
      "辣",
      "朋友",
      "mexican",
      "spicy",
      "casual"
    ],
    desc: "氣氛熱鬧，主打香辣墨西哥菜。",
    desc_en: "Vibrant Mexican food with bold spicy flavors.",
    map: "https://maps.google.com/?q=22.2830,114.1568",
    image_url: "https://images.unsplash.com/photo-1600891964092-4316c288032e",
    lat: 22.283,
    lng: 114.1568
  },
  {
    id: "MK01",
    name: "點心園",
    en_name: "Dim Sum Garden",
    area: "旺角",
    area_en: "Mong Kok",
    cuisine: "點心",
    cuisine_en: "Dim Sum",
    price: "$",
    score: 4,
    tags: [
      "點心",
      "中式",
      "早餐",
      "dimsum",
      "chinese",
      "cheap"
    ],
    desc: "傳統點心，平價又好味。",
    desc_en: "Classic dim sum at affordable prices.",
    map: "https://maps.google.com/?q=22.3208,114.1690",
    image_url: "https://images.unsplash.com/photo-1553621042-f6e147245754",
    lat: 22.3208,
    lng: 114.169
  },
  {
    id: "MK02",
    name: "漢堡實驗室",
    en_name: "Burger Lab",
    area: "旺角",
    area_en: "Mong Kok",
    cuisine: "美式漢堡",
    cuisine_en: "Burger",
    price: "$$",
    score: 3,
    tags: [
      "漢堡",
      "快餐",
      "burger",
      "american",
      "casual"
    ],
    desc: "大份量漢堡，食得夠飽。",
    desc_en: "Big juicy burgers, very filling.",
    map: "https://maps.google.com/?q=22.3200,114.1685",
    image_url: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd",
    lat: 22.32,
    lng: 114.1685
  }
];
